name: song_book
description: A simple song-book persistent web app
version: 0.0.1
homepage: https://github.com/ppetr/song-book

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  pwa: ^0.2.1
  angular: ^6.0.0-alpha
  angular_components: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
